/* File generated by create_simplyv_conf_header.py */

#ifndef __SIMPLYV_CONF_H__
#define __SIMPLYV_CONF_H__

#include <stdint.h>

// Address of configured peripherals
#define _peripheral_BRAM_start  0x0000000000000000u
#define _peripheral_BRAM_end    0x0000000000010000u
#define _peripheral_DM_mem_start  0x0000000000010000u
#define _peripheral_DM_mem_end    0x0000000000020000u
#define _peripheral_CLINT_start  0x0000000000030000u
#define _peripheral_CLINT_end    0x0000000000040000u
#define _peripheral_CDMA_start  0x0000000000040000u
#define _peripheral_CDMA_end    0x0000000000050000u
#define _peripheral_HLS_CONTROL_start  0x0000000000050000u
#define _peripheral_HLS_CONTROL_end    0x0000000000060000u
#define _peripheral_CMAC_CSR_start  0x0000000000100000u
#define _peripheral_CMAC_CSR_end    0x0000000000140000u
#define _peripheral_DDR4CH1_start  0x0000000001000000u
#define _peripheral_DDR4CH1_end    0x0000000002000000u
#define _peripheral_PLIC_start  0x0000000004000000u
#define _peripheral_PLIC_end    0x0000000008000000u
#define _peripheral_UART_start  0x0000000000020000u
#define _peripheral_UART_end    0x0000000000020010u
#define _peripheral_TIM0_start  0x0000000000020020u
#define _peripheral_TIM0_end    0x0000000000020040u
#define _peripheral_TIM1_start  0x0000000000020040u
#define _peripheral_TIM1_end    0x0000000000020060u
#define _peripheral_m_acc_start  0x0000000000080000u
#define _peripheral_m_acc_end    0x0000000000090000u
#define _peripheral_DDR4CH0_start  0x0000000000090000u
#define _peripheral_DDR4CH0_end    0x00000000000a0000u

// Enabled devices
#define TIM_IS_ENABLED 1
#define UART_IS_ENABLED 1

#endif // __SIMPLYV_CONF_H__
