#ifndef SIMPLYV_H
#define SIMPLYV_H

#include "stdlib.h"

// This header is autogenerated based on project configuration
#include "simplyv_conf.h"

#include "irq_handlers.h"
#include "plic.h"
#ifdef GPIO_IN_IS_ENABLED
#include "xlnx_gpio_in.h"
#endif

#ifdef GPIO_OUT_IS_ENABLED
#include "xlnx_gpio_out.h"
#endif

#ifdef TIM_IS_ENABLED
#include "xlnx_tim.h"
#endif

#include "xlnx_cdma.h"
#include "tinyIO.h"

enum{
    SIMPLYV_OK = 0,
    SIMPLYV_ERROR
};

static inline void simplyv_init()
{
    // TinyIO init
    uintptr_t uart_base_address = (uintptr_t)_peripheral_UART_start;
    tinyIO_init(uart_base_address);

    // PLIC init
    plic_init();
}

#endif
